/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package irrgarten.UI;

import irrgarten.Directions;
import irrgarten.GameState;
//import java.awt.Font;

/**
 *
 * @author jorge
 */
public class GraphicalUI extends javax.swing.JFrame implements UI{
    
    private Cursors cursors;
  //  private Font font = new Font(Font.MONOSPACED, Font.PLAIN, 17);
    
    /**
     * Creates new form GraphicalUI
     */
    public GraphicalUI() {
        initComponents();
        setVisible(true);
        cursors = new Cursors(this,true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        labyrinth = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        players = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        monsters = new javax.swing.JTextArea();
        LabyrinthLabel = new javax.swing.JLabel();
        PlayersLabel = new javax.swing.JLabel();
        MonstersLabel = new javax.swing.JLabel();
        Info = new javax.swing.JLabel();
        currentPlayer = new javax.swing.JTextField();
        winner = new javax.swing.JTextField();
        CurrentPlayerLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        logInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labyrinth.setColumns(20);
        labyrinth.setRows(5);
        jScrollPane1.setViewportView(labyrinth);

        players.setColumns(20);
        players.setRows(5);
        jScrollPane2.setViewportView(players);

        monsters.setColumns(20);
        monsters.setRows(5);
        jScrollPane3.setViewportView(monsters);

        LabyrinthLabel.setText("Labyrinth:");

        PlayersLabel.setText("Players:");

        MonstersLabel.setText("Monsters:");

        Info.setText("Info:");

        currentPlayer.setText("jTextField1");

        winner.setText("jTextField1");

        CurrentPlayerLabel.setText("CurrentPlayer:");

        jLabel1.setText("Winner:");

        logInfo.setColumns(20);
        logInfo.setRows(5);
        jScrollPane4.setViewportView(logInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Info)
                    .addComponent(LabyrinthLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CurrentPlayerLabel)
                        .addGap(18, 18, 18)
                        .addComponent(currentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addComponent(winner, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MonstersLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PlayersLabel))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabyrinthLabel)
                    .addComponent(PlayersLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Info)
                    .addComponent(MonstersLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(winner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CurrentPlayerLabel)
                            .addComponent(currentPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    public void showGame(GameState gameState) {
        labyrinth.setText(gameState.getLabyrinthv());
      //  labyrinth.setFont(font);
        players.setText(gameState.getPlayers());
        monsters.setText(gameState.getMonsters());
        currentPlayer.setText(String.valueOf(gameState.getCurrentPlayer()));
        winner.setText(gameState.getWinner());
        logInfo.setText(gameState.getLog());
        repaint();
    }
    
    @Override
    public Directions nextMove() {
        return cursors.getDirection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CurrentPlayerLabel;
    private javax.swing.JLabel Info;
    private javax.swing.JLabel LabyrinthLabel;
    private javax.swing.JLabel MonstersLabel;
    private javax.swing.JLabel PlayersLabel;
    private javax.swing.JTextField currentPlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea labyrinth;
    private javax.swing.JTextArea logInfo;
    private javax.swing.JTextArea monsters;
    private javax.swing.JTextArea players;
    private javax.swing.JTextField winner;
    // End of variables declaration//GEN-END:variables
}
